# Generated by Django 5.0 on 2023-12-20 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name_img',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded at'),
        ),
    ]
