# Generated by Django 5.0 on 2023-12-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_image', '0002_image_name_img_alter_image_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name_img',
        ),
    ]
