# Generated by Django 5.0 on 2023-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_image', '0003_remove_image_name_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_img',
            field=models.ImageField(upload_to='image/', verbose_name='File image'),
        ),
    ]
